-- ════════════════════════════════════════════════════════════════════
-- VELUM · Fase A.6 — Modelo de datos de Recovery (wellness · spa · fisio)
-- ────────────────────────────────────────────────────────────────────
-- El modelo nuevo: cita 1-a-1 POR RECURSO (no clase grupal).
--   recursos   = sauna, cabina de crio, camilla de masaje, bota de compresión
--   protocolos = plantillas de recuperación (pasos encadenados)
--   citas      = reservas 1-a-1 de un recurso en una fecha/hora
-- ADITIVO: tablas nuevas, no tocan nada. RLS multi-tenant (gym_id).
-- ════════════════════════════════════════════════════════════════════

-- ── RECURSOS ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.recursos (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gym_id       bigint NOT NULL,
  nombre       text NOT NULL,
  tipo         text,                       -- sauna | crioterapia | masaje | compresion | otro
  duracion_min integer NOT NULL DEFAULT 30,
  activo       boolean NOT NULL DEFAULT true,
  sort_order   integer DEFAULT 0,
  created_at   timestamptz DEFAULT now()
);
ALTER TABLE public.recursos ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.recursos TO authenticated;
-- Cualquier usuario del gym (admin/staff o cliente) ve sus recursos…
CREATE POLICY recursos_select ON public.recursos FOR SELECT TO authenticated
USING (is_superadmin() OR gym_id = auth_gym_id());
-- …pero solo admin/staff los administra.
CREATE POLICY recursos_write ON public.recursos FOR ALL TO authenticated
USING (is_superadmin() OR ((gym_id = auth_gym_id()) AND (auth_app_rol() = ANY (ARRAY['admin','staff','superadmin']))))
WITH CHECK (is_superadmin() OR ((gym_id = auth_gym_id()) AND (auth_app_rol() = ANY (ARRAY['admin','staff','superadmin']))));

-- ── PROTOCOLOS ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.protocolos (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gym_id     bigint NOT NULL,
  nombre     text NOT NULL,
  pasos      text,                          -- descripción / pasos encadenados
  activo     boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.protocolos ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.protocolos TO authenticated;
CREATE POLICY protocolos_select ON public.protocolos FOR SELECT TO authenticated
USING (is_superadmin() OR gym_id = auth_gym_id());
CREATE POLICY protocolos_write ON public.protocolos FOR ALL TO authenticated
USING (is_superadmin() OR ((gym_id = auth_gym_id()) AND (auth_app_rol() = ANY (ARRAY['admin','staff','superadmin']))))
WITH CHECK (is_superadmin() OR ((gym_id = auth_gym_id()) AND (auth_app_rol() = ANY (ARRAY['admin','staff','superadmin']))));

-- ── CITAS — espeja la seguridad de 'reservas' (admin/staff · cliente · portal) ──
CREATE TABLE IF NOT EXISTS public.citas (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  gym_id         bigint NOT NULL,
  recurso_id     bigint,
  cliente_id     bigint,
  cliente_nombre text NOT NULL,
  portal_token   text,
  fecha          date NOT NULL,
  hora_inicio    text,                       -- "17:00"
  duracion_min   integer,
  protocolo_id   bigint,
  protocolo      text,                        -- snapshot del nombre del protocolo
  estado         text DEFAULT 'agendada',     -- agendada | completada | cancelada | no_show
  notas          text,
  created_at     timestamptz DEFAULT now()
);
ALTER TABLE public.citas ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.citas TO authenticated;

CREATE POLICY citas_select ON public.citas FOR SELECT TO authenticated
USING (
  is_superadmin()
  OR ((gym_id = auth_gym_id()) AND (auth_app_rol() = ANY (ARRAY['admin','staff','superadmin'])))
  OR (cliente_id = auth_cliente_id())
  OR (portal_token = (auth.jwt() ->> 'portal_token'))
);
CREATE POLICY citas_insert ON public.citas FOR INSERT TO authenticated
WITH CHECK (
  is_superadmin()
  OR ((gym_id = auth_gym_id()) AND (auth_app_rol() = ANY (ARRAY['admin','staff','superadmin'])))
  OR ((cliente_id = auth_cliente_id()) AND (gym_id = auth_gym_id()))
  OR ((portal_token = (auth.jwt() ->> 'portal_token')) AND (gym_id = auth_gym_id()))
);
CREATE POLICY citas_update ON public.citas FOR UPDATE TO authenticated
USING (
  is_superadmin()
  OR ((gym_id = auth_gym_id()) AND (auth_app_rol() = ANY (ARRAY['admin','staff','superadmin'])))
  OR (cliente_id = auth_cliente_id())
  OR (portal_token = (auth.jwt() ->> 'portal_token'))
);
CREATE POLICY citas_delete ON public.citas FOR DELETE TO authenticated
USING (
  is_superadmin()
  OR ((gym_id = auth_gym_id()) AND (auth_app_rol() = ANY (ARRAY['admin','staff','superadmin'])))
  OR (cliente_id = auth_cliente_id())
  OR (portal_token = (auth.jwt() ->> 'portal_token'))
);

CREATE INDEX IF NOT EXISTS idx_citas_lookup   ON public.citas (gym_id, fecha, recurso_id, estado);
CREATE INDEX IF NOT EXISTS idx_recursos_gym   ON public.recursos (gym_id, activo, sort_order);

-- ── ROLLBACK ──
-- DROP TABLE IF EXISTS public.citas CASCADE;
-- DROP TABLE IF EXISTS public.protocolos CASCADE;
-- DROP TABLE IF EXISTS public.recursos CASCADE;
